url: 'https://ascl1u.github.io'
include: [CNAME]
baseurl: ''
title: 'Andy Liu'

plugins:
  - jekyll-postcss

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..3
social:
  twitter: lscqtds
  linkedin: andy-liu-sic
  scholar: N/A
  github: ascl1u
  email: a.liu27568@gmail.com

permalink: /blog/:title/

google_analytics:

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
